name: I2::Dev::Tests

on:
  pull_request:
    branches: [main]
    paths:
      - '**.rs'
      - '**.json'
      - '**.toml'
      - '**.lock'
      - '**.py'
      - '.github/workflows/iroha2-dev-pr.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CLIENT_CLI_DIR: "/__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}/test"
  DOCKER_COMPOSE_PATH: defaults
  TEST_DIR: "tmp/test"
  IROHA_BIN: "iroha"
  IROHA_CONTAINER: "defaults-irohad0-1"
  PYTHON_VERSION: "3.11"
  POETRY_PATH: "/root/.local/bin/poetry"

jobs:
  torii-api-client-cli-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: Test docker-compose.single.yml
        run: |
          docker compose -f ${{ env.DOCKER_COMPOSE_PATH }}/docker-compose.single.yml up --wait || exit 1
          docker compose -f ${{ env.DOCKER_COMPOSE_PATH }}/docker-compose.single.yml down
      - name: Wipe docker-compose.yml containers
        if: always()
        run: docker compose -f ${{ env.DOCKER_COMPOSE_PATH }}/docker-compose.yml down
