name: I2::CI::Raven CI/CD Scan

on:
  workflow_dispatch:
    inputs:
      IROHA2_REPO:
        required: true
        default: hyperledger/iroha

jobs:
  raven-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Raven Repository
      run: git clone --branch feature_single_repo https://github.com/sadreck/raven.git
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install Raven
      run: pip3 install raven-cycode

    - name: Set up Redis and Neo4j
      run: |
        docker run -d --name raven-neo4j -p7474:7474 -p7687:7687 --env NEO4J_AUTH=neo4j/123456789 --volume raven-neo4j:/data neo4j:5.12
        docker run -d --name raven-redis -p6379:6379 --volume raven-redis:/data redis:7.2.1
  
    - name: Download Workflows
      run: cd raven && python3 main.py download repo --token ${{ secrets.GITHUB_TOKEN }} --debug --clean-redis --repo-name ${{ github.event.inputs.IROHA2_REPO }}

    - name: Index Workflows
      run: raven index

    - name: Generate Report
      run: raven report --queries-path raven/library --format json > raven-report.json

    - name: Print Report
      run: cat raven-report.json

    - name: Upload Report
      uses: actions/upload-artifact@v4
      with:
        name: raven-report
        path: raven-report.json
